<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(TargetFramework)-android</TargetFramework>
    <ApplicationId>com.$(Authors).$(Product.ToLowerInvariant())</ApplicationId>
    <ApplicationIdTitle>$(Product)</ApplicationIdTitle>
    <SupportedOSPlatformVersion>30</SupportedOSPlatformVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>$(Version)</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release' And Exists('$(MSBuildProjectDirectory)/android-release.keystore')">
    <AndroidKeyStore>true</AndroidKeyStore>
    <AndroidSigningKeyStore>$(MSBuildProjectDirectory)/android-release.keystore</AndroidSigningKeyStore>
    <AndroidSigningKeyAlias>$(Product.ToLowerInvariant())</AndroidSigningKeyAlias>
    <AndroidSigningStorePass>cfs-release-2026</AndroidSigningStorePass>
    <AndroidSigningKeyPass>cfs-release-2026</AndroidSigningKeyPass>
  </PropertyGroup>

  <ItemGroup>
    <AndroidResource Include="..\CalculateFolderSize.UI.Shared\Assets\Icon.png">
      <Link>Resources\drawable\icon.png</Link>
    </AndroidResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalculateFolderSize.UI.Shared\CalculateFolderSize.UI.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NReco.Logging.File" />
  </ItemGroup>

</Project>
